[package]
name = "zae-a2600"
version = "0.1.0"
edition = "2021"
authors = ["versonr7"]
description = "Atari 2600 emulator core"
license = "GPL-3.0-only"

[lib]
name = "zae_a2600"
crate-type = ["lib"]

[dependencies]
za-math = { path = "../../ZAVOGLES-GUI/za-math" }
za-gles = { path = "../../ZAVOGLES-GUI/za-gles" }
za-xmb = { path = "../../ZAVOGLES-GUI/za-xmb" }
